# Generated by Django 4.2.1 on 2023-09-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_site', '0002_rename_duration_seconds_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='last_viewed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
